Phần 1:

In [1]:
import numpy as np

arr = np.full((3, 3), True)
print("Array arr (3x3 với các giá trị True):\n", arr)

Array arr (3x3 với các giá trị True):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Phần 2:

In [2]:
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape((3, 3))
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nArray arr_2D (sau khi chuyển cột 1 và cột 3):\n", arr_2D)


Array arr_2D (sau khi chuyển cột 1 và cột 3):
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


Phần 3:

In [3]:
arr_2D[[0, 1, 2], :] = arr_2D[[1, 0, 2], :]
print("\nArray arr_2D (sau khi chuyển dòng 1 và dòng 2):\n", arr_2D)


Array arr_2D (sau khi chuyển dòng 1 và dòng 2):
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


Phần 4:

In [4]:
arr_2D = np.flip(arr_2D, axis=0)
print("\nArray arr_2D (sau khi đảo ngược các dòng):\n", arr_2D)


Array arr_2D (sau khi đảo ngược các dòng):
 [[8 7 6]
 [2 1 0]
 [5 4 3]]


Phần 5:

In [5]:
arr_2D = np.flip(arr_2D, axis=1)
print("\nArray arr_2D (sau khi đảo ngược các cột):\n", arr_2D)


Array arr_2D (sau khi đảo ngược các cột):
 [[6 7 8]
 [0 1 2]
 [3 4 5]]


Phần 6:

In [6]:
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print("\nKiểm tra có giá trị rỗng trong array không:", has_nan)


Kiểm tra có giá trị rỗng trong array không: True


Phần 7:

In [7]:
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nArray arr_2D_null (sau khi thay thế giá trị null bằng 0):\n", arr_2D_null)


Array arr_2D_null (sau khi thay thế giá trị null bằng 0):
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
